# Generated by Django 4.2.3 on 2023-08-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Imię')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('subject', models.CharField(max_length=100, verbose_name='Temat')),
            ],
        ),
    ]
